california_housing.zip: california_housing.py
	mkdir california_housing
	python california_housing.py
	zip -r california_housing.zip california_housing 
	rm -rf california_housing
	du -h california_housing.zip
